2022-08-30 20:52:23.974 WARNING (MainThread) [homeassistant.components.switch] Platform broadlink not ready yet: None; Retrying in background in 30 seconds
2022-08-30 20:52:24.791 ERROR (SyncWorker_5) [openwrt.ubus.interface] api_call exception: HTTPConnectionPool(host='192.168.1.2', port=80): Max retries exceeded with url: /ubus (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f74c95e8940>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2022-08-30 20:52:24.815 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy ubus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 248, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/ubus/device_tracker.py", line 43, in get_scanner
    scanner = DnsmasqUbusDeviceScanner(config[DOMAIN])
  File "/usr/src/homeassistant/homeassistant/components/ubus/device_tracker.py", line 148, in __init__
    super().__init__(config)
  File "/usr/src/homeassistant/homeassistant/components/ubus/device_tracker.py", line 91, in __init__
    self.success_init = self.ubus.connect() is not None
  File "/usr/local/lib/python3.10/site-packages/openwrt/ubus/interface.py", line 161, in connect
    if API_UBUS_RPC_SESSION in login:
TypeError: argument of type 'NoneType' is not iterable
2022-08-30 21:38:34.905 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-30 21:38:34.910 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 21:38:34.910 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 21:38:34.914 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 21:38:34.914 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-30 21:38:34.917 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-30 21:42:34.916 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 21:42:34.921 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 21:42:34.922 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-30 22:10:04.976 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 22:10:04.985 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 22:10:04.986 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-30 22:32:35.017 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 22:32:35.018 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 22:32:35.021 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-30 22:35:35.022 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-30 22:35:35.032 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 22:35:35.033 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:03:05.069 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:03:05.071 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:03:05.073 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:10:35.083 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-30 23:10:35.086 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:10:35.088 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:17:35.094 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-30 23:17:35.097 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:17:35.099 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:32:35.122 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-30 23:32:35.124 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:32:35.124 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:32:35.125 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:32:35.128 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:32:35.129 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:34:05.126 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:34:05.136 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:34:05.137 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:40:05.139 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:40:05.146 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:40:05.148 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:48:35.157 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:48:35.164 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:48:35.166 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:56:05.169 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:56:05.179 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:56:05.180 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:56:35.170 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:56:35.173 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:56:35.174 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-30 23:57:05.170 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-30 23:57:05.179 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-30 23:57:05.183 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:00:00.005 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.bing_ju_switch or it is/they are currently not available
2022-08-31 00:07:05.187 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 00:07:05.189 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 00:07:05.192 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:07:05.193 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:07:05.195 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:07:05.196 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:09:05.192 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 00:09:05.201 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:09:05.203 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:09:35.192 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 00:09:35.201 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:09:35.203 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:14:05.200 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 00:14:05.202 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:14:05.204 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:14:35.201 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 00:14:35.210 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:14:35.211 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:18:05.209 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 00:18:05.217 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:18:05.219 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:22:35.216 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 00:22:35.226 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:22:35.227 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:23:05.217 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 00:23:05.225 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:23:05.227 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:32:35.234 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 00:32:35.244 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:32:35.246 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:33:05.236 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 00:33:05.245 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 00:33:05.247 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-31 00:50:54.003 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 四位排插 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-31 01:29:35.355 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 01:29:35.363 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 01:29:35.364 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-31 01:35:59.004 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 四位排插 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-31 02:16:05.453 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 02:16:05.453 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 02:16:05.456 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-31 02:16:35.454 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 02:16:35.454 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 02:16:35.457 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-31 02:39:35.501 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 02:39:35.506 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 02:39:35.507 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-31 03:02:04.004 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 四位排插 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-31 04:00:00.005 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-08-31 05:52:35.943 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 05:52:35.946 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 05:52:35.947 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-31 05:55:35.948 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 05:55:35.949 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 05:55:35.951 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 05:55:35.952 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-31 05:55:35.956 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 05:55:35.957 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-31 06:00:00.012 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.bing_ju_switch or it is/they are currently not available
2022-08-31 06:11:09.004 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 四位排插 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-31 06:21:39.468 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:21:41.390 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:21:42.491 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:21:46.580 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:21:56.091 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140138934885328] Disconnected: Did not receive auth message within 10 seconds
2022-08-31 06:22:00.663 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140137377759088] Disconnected: Did not receive auth message within 10 seconds
2022-08-31 06:22:03.268 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:22:06.533 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140137377057568] Disconnected: Did not receive auth message within 10 seconds
2022-08-31 06:22:13.803 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:22:23.091 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140138934973968] Disconnected: Did not receive auth message within 10 seconds
2022-08-31 06:22:29.276 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:22:33.615 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140138934883936] Disconnected: Did not receive auth message within 10 seconds
2022-08-31 06:22:49.193 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140138934926016] Disconnected: Did not receive auth message within 10 seconds
2022-08-31 06:23:02.307 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:23:03.074 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/api/websocket'. (Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Mobile/HomeAssistant, like Safari)
2022-08-31 06:23:03.118 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:23:05.177 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 232.45.205.221.adsl-pool.sx.cn (221.205.45.232). Requested URL: '/auth/token'. (Home Assistant/2022.3 (io.robbie.HomeAssistant; build:2022.358; iOS 14.2.0) Alamofire/5.4.4)
2022-08-31 06:23:25.122 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140138934968592] Disconnected: Did not receive auth message within 10 seconds
2022-08-31 07:13:36.129 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 07:13:36.138 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 07:13:36.139 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-31 07:30:36.170 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 07:30:36.177 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 07:30:36.179 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-31 08:28:06.297 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 08:28:06.307 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 08:28:06.308 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-31 08:57:06.364 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 08:57:06.374 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 08:57:06.375 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-31 09:00:00.012 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-08-31 09:00:06.371 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-31 09:00:06.376 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 09:00:06.378 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-31 09:45:31.303 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-31 09:48:06.480 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 09:48:06.487 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 09:48:06.489 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-31 10:16:06.545 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 10:16:06.555 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 10:16:06.556 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-31 11:49:13.005 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching s2 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-31 11:52:35.014 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching s3 (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-31 12:15:06.901 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-31 12:15:06.910 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-31 12:15:07.210 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-31 13:38:40.004 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching s3 (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
